name: Solar System Workflow
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
      - feature/*
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: '${{ secrets.MONGO_PASSWORD }}'

permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: >-
            ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
